# default
spring:
  profiles:
    active: test
    group:
      prod: prod, auth, prod-db
      local: local, auth, common
      test: test, auth, common

---
# common 환경
spring:
  config:
    activate:
      on-profile: common

  devtools:
    livereload:
      enabled: true

# cors 설정
cors:
  allowedOrigins: 'http://localhost:3000'
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowedHeaders: '*'
  maxAgeSec: 3600

server:
  port: 8080

---
# test 환경
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE  # db 주소 고정
    sql:
      init:
        data-locations: classpath:data-for-h2.sql # 시작할때 실행시킬 script
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    #  show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
---
# local 환경
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diabetes?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  sql:
    init:
      data-locations: classpath:data-for-mysql.sql # 시작할때 실행시킬 script -> 실행이 안됨, 확인 필요
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    generate-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update # 데이터를 쌓아두기 위해, update로 지정
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

---
# prod 환경
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none
logging:
  level:
    #    root: DEBUG
    org:
      springframework:
        security: DEBUG

# cors 설정
cors:
  allowedOrigins: 'http://localhost:80'
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowedHeaders: '*'
  maxAgeSec: 3600

# TODO 포트 설정 동적으로 할당 가능하게 변경할 필요
server:
  port: 8080