# default
spring:
  profiles:
    active: dev
    group:
      prod: prod, auth, prod-db
      dev: auth, prod-db, dev, common
      local: local, auth, common
      test: test, auth, common

---
# common 환경
spring:
  config:
    activate:
      on-profile: common
  devtools:
    livereload:
      enabled: true

# cors 설정
cors:
  allowedOrigins: 'http://localhost:3000'
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowedHeaders: '*'
  maxAgeSec: 3600
server:
  port: 8080

# 로그인 성공/실패 리디렉션 주소
authRedirection:
  successUrl: 'http://localhost:3000/login/redirect'
  failureUrl: 'http://localhost:3000/login'
---
# test 환경
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE # db 주소 고정
  sql:
    init:
      data-locations: classpath:data-for-h2.sql # 시작할때 실행시킬 script
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
---
# local 환경
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diabetes?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  sql:
    init:
      data-locations: classpath:data-for-mysql.sql # 시작할때 실행시킬 script -> 실행이 안됨, 확인 필요
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update # 데이터를 쌓아두기 위해, update로 지정
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

---
# dev 환경
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    hibernate:
      ddl-auto: update
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
# server:
#   servlet:
#     session:
#       cookie:
#         domain: localhost
#        same-site: none
#        secure: true

---
# prod 환경
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

# cors 설정
cors:
  allowedOrigins: 'https://gl-diabetes.shop'
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowedHeaders: '*'
  maxAgeSec: 3600

# 로그인 성공/실패 리디렉션 주소
authRedirection:
  successUrl: 'https://gl-diabetes.shop/login/redirect'
  failureUrl: 'https://gl-diabetes.shop/login'

# TODO 포트 설정 동적으로 할당 가능하게 변경할 필요
server:
  port: 8080
#  servlet:
#    session:
#      cookie:
#        same-site: none
